/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Karolina Renkiewicz (https://sketchfab.com/KarolinaRenkiewicz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bitcoin-ff17dab54b044d789d05ae7c8dfb9808
Title: Bitcoin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/scene.gltf') as any

  const meshRef = useRef<THREE.Mesh>(null)

  useFrame((state, delta) => {
    //meshRef.current!.rotation.x -= 0.01
    meshRef.current!.rotation.y -= 0.01
    //meshRef.current!.rotation.z += 0.01
  }) 

  return (
    <group {...props} dispose={null}>
      <mesh 
        ref={meshRef}
        scale={[0.9, 0.9, 0.9]}
        geometry={nodes.Cylinder002__0.geometry} 
        material={materials['Scene_-_Root']} 
        position={[0, 0, 0]} 
      />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
